name: flutter_test_example
description: A Flutter Package (Demo) to render spotlight_ant.
homepage: https://github.com/evan361425/flutter-spotlight-ant

version: 1.0.0+1

publish_to: "none"

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  spotlight_ant:
    path: ../

dev_dependencies:
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
