name: spotlight_ant
version: 0.2.0
description: >-
  Spotlight the widget by wrapping it
repository: https://github.com/evan361425/flutter-spotlight-ant
environment:
  flutter: ">=3.0.0-0"
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
