name: Publish package

on:
  # Pub.dev only allows automated publishing from GitHub Actions
  # when the workflow is triggered by pushing a git tag to GitHub.
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    name: "Publish to pub.dev"
    permissions:
      id-token: write
    # Specify the github actions deployment environment
    environment: pub.dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          cache: true
          channel: "stable"
      - name: Publish - dry run
        run: flutter pub publish --dry-run
      - name: Publish
        run: flutter pub publish --force
