name: Publish package

on:
  # Pub.dev only allows automated publishing from GitHub Actions
  # when the workflow is triggered by pushing a git tag to GitHub.
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    # followed by
    # https://dart.dev/tools/pub/automated-publishing#configuring-a-github-action-workflow-for-publishing-to-pubdev
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    permissions:
      id-token: write
    with:
      # Specify the github actions deployment environment
      environment: pub.dev
