name: Publish package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
        with:
          # Specify the github actions deployment environment
          environment: pub.dev
