name: Publish package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.x"
          cache: true
          channel: "stable"
      - name: Publish - dry run
        run: flutter pub publish --dry-run
      # Publishing...
      - name: Publish to pub.dev
        run: flutter pub publish -f
