name: Publish package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          # Specify the github actions deployment environment
          environment: pub.dev
      - name: Publish - dry run
        run: dart pub publish --dry-run
      # Publishing...
      - name: Publish to pub.dev
        run: dart pub publish -f
