name: Publish package

on:
  push:
    tags:
      - "v*"

jobs:
  gh-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # Get flutter dependencies.
      - name: Install dependencies
        run: flutter pub get

      - name: Build web
        working-directory: ./example
        run: flutter build web --release

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./example/build/web
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Publish
        uses: sakebook/actions-flutter-pub-publisher@v1.4.1
        with:
          credential: ${{ secrets.PUB_CREDENTIALS }}
